title: Raspberry Turk
email: contact@joeymeyer.com
description: >
  The Raspberry Turk is a robot that can play chess—it's entirely open source, based on
  Raspberry Pi, and inspired by the 18th century chess playing machine, the Mechanical Turk.
baseurl: ""
url: "http://www.raspberryturk.com"
author: Joey Meyer
twitter_username: joey_meyer
github_username:  joeymeyer
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .ruby-version
  - CNAME
