title: Raspberry Turk
email: contact@joeymeyer.com
email_md5: d4632c9b35d2eeefde9e50190da81994
description: >
  The Raspberry Turk is a robot that can play chess—it's entirely open source, based on
  Raspberry Pi, and inspired by the 18th century chess playing machine, the Mechanical Turk.
baseurl: ""
url: "http://www.raspberryturk.com"
author: Joey Meyer
twitter_username: joey_meyer
github_username:  joeymeyer
raspberryturk_github_repo: https://github.com/joeymeyer/raspberryturk
website_github_repo: https://github.com/raspberryturk/www.raspberryturk.com
google_analytics: UA-37250780-6
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .ruby-version
  - CNAME
  - LICENSE
